### PR TITLE
Fix lint warnings

### PR DESCRIPTION
**Pull request by remonh87**

### CODE REVIEW

**Comment by remonh87** [comment]
Fixes #16

**Comment by spkersten** [comment]
These warning are specific for the lint rules you have chosen and there are other lint rules requiring the opposite (i.e. the current code). So It would be better to add ignore-comments for the warnings.

**Comment by remonh87** [comment]
That can make sense.  Maybe it is still handy to remove the var from the hashcode generation so I will leave that one in if that is ok.

**Comment by spkersten** [comment]
It will cause the "omit type on local variable" in our code base. So, also there I would just add an ignore for the warning.

**Pull request closed without merging**
